/**
 * Created by thientran on 8/14/16.
 */

module.exports = Object.freeze({
  RES_USER_EXISTS: 5,
  RES_TYPE_JSON: 6,
  RES_USER_SIGNIN_SUCCESS: 10,
  CREATE_ACTIVE_CODE_FAIL:62,
  CREATE_ACTIVE_CODE_SUCCESS:63,
  RES_USER_SIGNIN_FAIL:66,

  NUMBER_LOW: 1000,
  NUMBER_HIGH:9999,
});
